### ISSUE TITLE
Unsuported redirects

### ISSUE THREAD

**Issue by ewallah** [QuentinFombaron/moodle-block_point_view#13]
Calling the require_login globally in your block_point_view.php and lib.php is not a good idea as everything what happens without being logged in (cron - sending of emails - calculation of grades - phpunit - behat, ...), is not functioning any more.

My logs are cluttered with messages like:
> Exception [moodle_exception] (blocks/point_view/lib.php -> require_login()) : Unsupported redirect detected, script execution terminated
> Exception [moodle_exception] (blocks/point_view/block_point_view.php -> require_login()) : Unsupported redirect detected, script execution terminated

**Comment by QuentinFombaron** [comment]
Corrected in the new version 😊
