### ISSUE TITLE
Tiles format

### ISSUE THREAD

**Issue by samuelPsicos** [QuentinFombaron/moodle-block_point_view#15]
Hola amigo

El Plugin no funciona correctamente con el el formato de curso "[Tiles format](https://moodle.org/plugins/format_tiles)", los emogis no aparecen para calificar la actividad.

¿como podria solucionar esto?

Muchas gracias amigo
![2020-04-25](https://user-images.githubusercontent.com/63096050/80285282-09ba5400-8724-11ea-94a4-ec568fd87aba.png)

**Comment by QuentinFombaron** [comment]
Hello @samuelPsicos ,

I will work on it ASAP :) We keep in touch!

**Comment by samuelPsicos** [comment]
Perfecto Muchas gracias amigo

**Comment by samuelPsicos** [comment]
Hola de nuevo amigo.

Quería saber si pudo solucionar el problema respecto a la visualización en el formato de curso Azulejos https://moodle.org/plugins/format_tiles.

Muchas gracias y un salud y gran trabajo

**Comment by luiggisanso** [comment]
Hi

Tested with :

- Point of view 1.4
- Tiles 3.9.0.6
- Moodle 3.9.2

It's ok now in all tiles BUT only if "format_tiles | usejavascriptnav" is turned off

But before it was ok only for the first tile with this mode

**Comment by samuelPsicos** [comment]
Hola

Muchisimas gracias gracias

voy a probarlo

**Comment by luiggisanso** [comment]
certainly a JS event or improvement...
I'm not dev...

**Comment by QuentinFombaron** [comment]
Hello,

I have not worked on Tiles format compatibility yet, it will be in the next update 💯 Thanks for you patience.

**Comment by luiggisanso** [comment]
PERFECT !!
![image (6)](https://user-images.githubusercontent.com/1565841/97292415-84873780-184b-11eb-8887-9f5bd7b2d19a.png)

**Comment by samuelPsicos** [comment]
Perfecto muchísimas gracias
