### ISSUE TITLE
Beta warning on stable version

### ISSUE THREAD

**Issue by upats** [QuentinFombaron/moodle-block_point_view#16]
Hi - this is an excellent plugin! I had a question suggestion. I've installed the stable 1.3 version. I notice when an instance of the block is created in a course it includes the following warning:

**_"It is important to know that you are testing the Beta version.
This plugin is developed by Quentin Fombaron (CLICK HERE to send me an email).
Thank you in advance for your returns and bug reports.

April 04th 2020 (version 1.1.0)_**

I wonder if this warning might be removed from future versions if it no longer applies. Some of my users might be worried about using a beta version in their live courses. Thanks!

**Comment by QuentinFombaron** [comment]
Hello @upats,

You’re right thank you for your feedback, I’ll update the default message today 😊 You can modify the message in the block settings if you want.

**Comment by upats** [comment]
Hi Quentin, thanks - is there a way to do that globally so that teachers don't see if when they add a new block? I don't see anything in the settings under Site admin -> plugins -> blocks -> point of view.
