### ISSUE TITLE
filemanager.php

### ISSUE THREAD

**Issue by AurelienDM** [QuentinFombaron/moodle-block_point_view#2]
When activating "reactions" it leaves me with this error 
Exception : Argument 1 passed to file_get_all_files_in_draftarea() must be of the type integer, null given, called in [dirroot]/lib/form/filemanager.php on line 336
<img width="1123" alt="screenshot 2019-02-05 at 10 36 20" src="https://user-images.githubusercontent.com/29572435/52265033-6cfb7300-2933-11e9-990d-13c5ef6f8184.png">

**Comment by QuentinFombaron** [comment]
Corrected in the new version 😊
