### ISSUE TITLE
about moodle-block_point_view install problem

### ISSUE THREAD

**Issue by cool3690** [QuentinFombaron/moodle-block_point_view#21]
hello,my name is chi
I install this plugin  success. 
 
but emoji still can not show in my course....
I dont know where can I open it?
this is my post.
[https://moodle.org/mod/forum/discuss.php?d=423109](https://moodle.org/mod/forum/discuss.php?d=423109)
please help me.

thanks.

**Comment by cool3690** [comment]
I slove the problem thanks.

**Comment by cool3690** [comment]
sorry, I have one more question,
this emoji record is store in which DB table
I want to grab data and  statistics.
thanks

**Comment by FasihZafar** [comment]
> I slove the problem thanks.

@cool3690  can you please share on what steps you took to make it work. Thanks
