### ISSUE TITLE
Synchronize plugin version in Moodle and in Git repo.

### ISSUE THREAD

**Issue by chyrka** [QuentinFombaron/moodle-block_point_view#27]
Thank you for developing additional features for Moodle. I installed this plugin from the archive (downloaded from Moodle site), but I prefer the Git repo. Could you please add new tags for releases to the Git repository as it is very difficult to keep track of updates to this plugin?

The latest version in Git is v1.5.0
The latest version on Moodle site is 2.0

**Comment by Astor-Bizard** [comment]
Hello,

Sorry for the inconvenience.
This project is now maintained by me, and has been permanently moved to a location where it will be able to keep being maintained.
You can find it here: https://gricad-gitlab.univ-grenoble-alpes.fr/moodle-plugins/moodle-block_point_view.git

Thank you for your understanding,
Astor

**Comment by chyrka** [comment]
Thanks a lot for your response.
