### ISSUE TITLE
«Reset reactions» fails (TypeError)

### ISSUE THREAD

**Issue by flo-thrd** [QuentinFombaron/moodle-block_point_view#4]
Resetting all the reactions in a course (from the block settings) throws an exception.

* php error log and traceback:

> Default exception handler: Exception - Argument 2 passed to block_point_view_external::update_db() must be of the type integer, null given, called in [dirroot]/lib/externallib.php on line 245
> Debug: 
> Error code: generalexceptionmessage
> * line 84 of /blocks/point_view/externallib.php: TypeError thrown
> * line 245 of /lib/externallib.php: call to block_point_view_external::update_db()
> * line 59 of /lib/ajax/service.php: call to external_api::call_external_function()

* Observed on : 

Moodle 3.6.3 (build 20190413) with PHP  7.0.33 running on Debian Stretch
Moodle 3.6.6 (build 20190909) with PHP 7.2.19 running on Linux Mint 19

* patch :

Removing scalar type hints for parameters $userid, $cmid, and $vote of method  block_point_view_external::update_db() (line 84 of point_view/externallib.php) appear to solve the problem (as these are null in the context of a course-wide reset), but might not be the cleanest solution.
Using nullable type ?int (if php>=7.1 available) instead also solves the problem but breaks compatibility with Moodle 3.6 (which requires php>=7.0 only)

**Comment by QuentinFombaron** [comment]
Corrected in the new version 😊
